server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://local/cache?characterEncoding=UTF8
    username: root
    password: root
  freemarker:
    cache: false
    suffix: .ftl
mybatis:
  mapper-locations: classpath:/mappers/*.xml
config:
  html-location: d:/dev/uploads/
